[tool.poetry]
name = "x4-advisor"
version = "0.1.0"
description = "X4 Foundations Advisor Application"
authors = ["Peter <peadarpol@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "x4_advisor", from = "src" }]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
